package com.cmc.user.service.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.cmc.user.facade.entity.User;

public class UserSqlProvider {

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table user
	 *
	 * @mbggenerated Sun Jun 12 11:10:07 CST 2016
	 */
	public String insertSelective(User record) {
		BEGIN();
		INSERT_INTO("user");

		if (record.getId() != null) {
			VALUES("id", "#{id,jdbcType=VARCHAR}");
		}

		if (record.getName() != null) {
			VALUES("name", "#{name,jdbcType=VARCHAR}");
		}

		if (record.getSex() != null) {
			VALUES("sex", "#{sex,jdbcType=CHAR}");
		}

		if (record.getAge() != null) {
			VALUES("age", "#{age,jdbcType=INTEGER}");
		}

		if (record.getCreateTime() != null) {
			VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
		}

		if (record.getUpdateTime() != null) {
			VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
		}

		if (record.getDeleteTime() != null) {
			VALUES("delete_time", "#{deleteTime,jdbcType=TIMESTAMP}");
		}

		if (record.getIsDelete() != null) {
			VALUES("is_delete", "#{isDelete,jdbcType=CHAR}");
		}

		if (record.getTemp1() != null) {
			VALUES("temp1", "#{temp1,jdbcType=VARCHAR}");
		}

		if (record.getTemp2() != null) {
			VALUES("temp2", "#{temp2,jdbcType=VARCHAR}");
		}

		if (record.getTemp3() != null) {
			VALUES("temp3", "#{temp3,jdbcType=VARCHAR}");
		}

		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table user
	 *
	 * @mbggenerated Sun Jun 12 11:10:07 CST 2016
	 */
	public String updateByPrimaryKeySelective(User record) {
		BEGIN();
		UPDATE("user");

		if (record.getName() != null) {
			SET("name = #{name,jdbcType=VARCHAR}");
		}

		if (record.getSex() != null) {
			SET("sex = #{sex,jdbcType=CHAR}");
		}

		if (record.getAge() != null) {
			SET("age = #{age,jdbcType=INTEGER}");
		}

		if (record.getCreateTime() != null) {
			SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
		}

		if (record.getUpdateTime() != null) {
			SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
		}

		if (record.getDeleteTime() != null) {
			SET("delete_time = #{deleteTime,jdbcType=TIMESTAMP}");
		}

		if (record.getIsDelete() != null) {
			SET("is_delete = #{isDelete,jdbcType=CHAR}");
		}

		if (record.getTemp1() != null) {
			SET("temp1 = #{temp1,jdbcType=VARCHAR}");
		}

		if (record.getTemp2() != null) {
			SET("temp2 = #{temp2,jdbcType=VARCHAR}");
		}

		if (record.getTemp3() != null) {
			SET("temp3 = #{temp3,jdbcType=VARCHAR}");
		}

		WHERE("id = #{id,jdbcType=VARCHAR}");

		return SQL();
	}
}