package com.cmc.programmer.service.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.cmc.programmer.facade.entity.Programmer;

public class ProgrammerSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table programmer
     *
     * @mbggenerated Fri Mar 17 13:37:44 CST 2017
     */
    public String insertSelective(Programmer record) {
        BEGIN();
        INSERT_INTO("programmer");
        
        if (record.getName() != null) {
            VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table programmer
     *
     * @mbggenerated Fri Mar 17 13:37:44 CST 2017
     */
    public String updateByPrimaryKeySelective(Programmer record) {
        BEGIN();
        UPDATE("programmer");
        
        if (record.getName() != null) {
            SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}