package com.cmc.programmer.service.dao;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.cmc.programmer.facade.entity.Programmer;

public interface ProgrammerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table programmer
     *
     * @mbggenerated Fri Mar 17 13:37:44 CST 2017
     */
    @Delete({
        "delete from programmer",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table programmer
     *
     * @mbggenerated Fri Mar 17 13:37:44 CST 2017
     */
    @Insert({
        "insert into programmer (name)",
        "values (#{name,jdbcType=VARCHAR})"
    })
    // SELECT LAST_INSERT_ID()：自动返回最后一个INSERT或UPDATE查询中AUTO_INCREMENT列设置的第一个表发生的值。
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Programmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table programmer
     *
     * @mbggenerated Fri Mar 17 13:37:44 CST 2017
     */
    @InsertProvider(type=ProgrammerSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Programmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table programmer
     *
     * @mbggenerated Fri Mar 17 13:37:44 CST 2017
     */
    @Select({
        "select",
        "id, name",
        "from programmer",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR)
    })
    Programmer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table programmer
     *
     * @mbggenerated Fri Mar 17 13:37:44 CST 2017
     */
    @UpdateProvider(type=ProgrammerSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Programmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table programmer
     *
     * @mbggenerated Fri Mar 17 13:37:44 CST 2017
     */
    @Update({
        "update programmer",
        "set name = #{name,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Programmer record);
}