package com.cmc.programmer.facade.entity;

public class Programmer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programmer.id
     *
     * @mbggenerated Fri Mar 17 13:37:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programmer.name
     *
     * @mbggenerated Fri Mar 17 13:37:44 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programmer.id
     *
     * @return the value of programmer.id
     *
     * @mbggenerated Fri Mar 17 13:37:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programmer.id
     *
     * @param id the value for programmer.id
     *
     * @mbggenerated Fri Mar 17 13:37:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programmer.name
     *
     * @return the value of programmer.name
     *
     * @mbggenerated Fri Mar 17 13:37:44 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programmer.name
     *
     * @param name the value for programmer.name
     *
     * @mbggenerated Fri Mar 17 13:37:44 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}